[mgr]
ratio=[3,3,10]
[opener]
edit = [
  { run = "nvim %s", block = true, desc = "nvim", for = "unix" }
]
markdown = [
  { run = "/home/osborne/.local/bin/mdcat --paginate %s1", block = true, desc = "Preview Markdown", for = "unix" }
]

[open]
prepend_rules = [
  { mime = "text/markdown", use = [ "markdown", "edit" ] },
  { url = "*.md", use = [ "markdown", "edit" ] },
  { url = "*.markdown", use = [ "markdown", "edit" ] },
]
